[package]
name = "statwalker"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam = "0.8.4"
itoa = "1.0.15"
num_cpus = "1.17.0"
clap = { version = "4.0", features = ["derive"] }
csv = "1.3"
time = { version = "0.3", features = ["local-offset", "macros"] }