[package]
name = "statwalker"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam = "0.8"
itoa = "1"
num_cpus = "1.17"
clap = { version = "4.0", features = ["derive"] }
csv = "1.3"
time = { version = "0.3", features = ["local-offset", "macros"] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bincode = { version = "2", features = ["derive"] }
blake3 = "1.8.2"
chrono = "0.4.41"
memchr = "2.7.5"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

