[package]
name = "walk"
version = "2.0.0"
edition = "2024"

[dependencies]
crossbeam = "0.8"
itoa = "1"
num_cpus = "1.17"
clap = { version = "4.5", features = ["derive"] }
csv = "1.3"
time = { version = "0.3", features = ["local-offset", "macros"] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bincode = { version = "2", features = ["derive"] }
blake3 = "1.8.2"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
memchr = "2.7"
axum = { version = "0.8.4", features = ["macros", "json"] }   # ← bumped
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.6", features = ["cors","fs"] }          # ← keep current; 0.6 works fine with axum 0.8

[target.'cfg(unix)'.dependencies]
libc = "0.2"

# [profile.release]
# lto = "thin"
# codegen-units = 1
# panic = "abort"
# opt-level = 3
