# .github/workflows/build-statwaker-rocky9.yml
name: Build statwaker (Rocky Linux 9, app/)

on:
  push:
    branches: [ master ]

jobs:
  build-rocky9:
    name: Rocky Linux 9 (x86_64)
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:9
      options: --privileged
    env:
      CARGO_HOME: /github/home/.cargo
      TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
      TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

    # All `run:` steps happen inside app/
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: System deps (GTK/WebKit & tooling for Tauri)
        run: |
          dnf -y update
          dnf -y install epel-release dnf-plugins-core
          dnf -y config-manager --set-enabled crb
          dnf -y install \
            git gcc-c++ make pkgconfig curl wget xz patchelf \
            glib2-devel gtk3-devel webkit2gtk4.1-devel librsvg2-devel \
            libappindicator-gtk3 libappindicator-gtk3-devel \
            openssl-devel

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: app/package-lock.json

      - name: Setup Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            /github/home/.cargo/registry
            /github/home/.cargo/git
            app/src-tauri/target
          key: rocky9-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            rocky9-cargo-

      - name: Install JS deps
        run: npm ci

      - name: Build frontend
        run: npm run build --if-present

      - name: Build Tauri bundle
        run: npx tauri build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: statwaker-rocky9
          path: app/src-tauri/target/**/release/bundle/**/*
          if-no-files-found: error
          