# .github/workflows/ci.yml
name: Dutopia CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.os }} build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            rs/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('rs/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build Rust project (rs/)
        working-directory: rs
        run: cargo build -r

      - name: Test Rust project (rs/)
        working-directory: rs
        run: cargo test -r

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install deps (browser/)
        working-directory: browser
        run: npm i

      - name: Build Svelte (browser/)
        working-directory: browser
        run: npm run build

      - name: Upload Rust artifacts
        uses: actions/upload-artifact@v4
        with:
          name: statwaker-${{ matrix.os }}-rust
          path: rs/target/**
          if-no-files-found: error

      - name: Upload Svelte artifacts
        uses: actions/upload-artifact@v4
        with:
          name: statwaker-${{ matrix.os }}-browser
          path: browser/build/**
          if-no-files-found: warn

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install cargo-edit
        run: cargo install cargo-edit

      - name: Bump patch version
        working-directory: rs
        run: cargo set-version --bump patch

      - name: Get new version
        id: cargo_version
        run: |
          VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Commit and push version bump
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add rs/Cargo.toml rs/Cargo.lock
          git commit -m "chore: bump version to $VERSION" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF_NAME}

      # - name: Create tag
      #   run: |
      #     git tag v${VERSION}
      #     git push origin v${VERSION}
